Repository SW-WordGarden/Android, pull requests merged in 2024-08, with the labels that each got.

#32 퀴즈 공유 기능 일부 구현(FCM)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sw/wordgarden/app/di/ServiceUseCaseModule.kt
  app/src/main/java/com/sw/wordgarden/app/di/UseCaseModule.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/Retrofit/Service.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSource.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSourceImpl.kt
  app/src/main/java/com/sw/wordgarden/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/repository/UserRepository.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/SendFirebaseTokenUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/SendFirebaseTokenUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/presentation/auth/AuthCodeHandlerActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/main/fcm/FirebaseMessagingService.kt
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ⚙️ chore, ✨ feature

#41 feature bottom_navigation
  app/build.gradle.kts
  app/src/main/java/com/sw/wordgarden/presentation/ui/main/MainActivity.kt
  app/src/main/res/drawable/bottom_garden.png
  app/src/main/res/drawable/bottom_home.png
  app/src/main/res/drawable/bottom_mypage.png
  app/src/main/res/drawable/bottom_quiz.png
  app/src/main/res/drawable/bottom_word.png
  app/src/main/res/drawable/selector_menu.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/bottom_navigation.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ feature

#48 design/home
  app/src/main/res/drawable/bg_home_gradient.xml
  app/src/main/res/drawable/bg_home_word_item.xml
  app/src/main/res/drawable/ic_alarm.png
  app/src/main/res/drawable/ic_non_alarm.png
  app/src/main/res/drawable/testflower.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🖌️ design code

#50 Feature/word
  app/src/main/java/com/sw/wordgarden/presentation/model/WordModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/DetailWordFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/LearningWordActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/WordAdapter.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/WordViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/wordFragment.kt
  app/src/main/res/drawable/detail_round_background.xml
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/item_word_background.xml
  app/src/main/res/drawable/selector_radio_button.xml
  app/src/main/res/layout/fragment_detail_word.xml
  app/src/main/res/layout/fragment_word.xml
  app/src/main/res/layout/item_word.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#59 FCM 알람 생성 및 조회 구현
  app/src/main/java/com/sw/wordgarden/app/di/DataSourceModule.kt
  app/src/main/java/com/sw/wordgarden/app/di/ServiceUseCaseModule.kt
  app/src/main/java/com/sw/wordgarden/app/di/UseCaseModule.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/local/LocalDataSource.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/local/LocalDataSourceImpl.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSource.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSourceImpl.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/retrofit/RetrofitClient.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/retrofit/Service.kt
  app/src/main/java/com/sw/wordgarden/data/dto/alarm/AlarmDto.kt
  app/src/main/java/com/sw/wordgarden/data/dto/user/LoginRequestDto.kt
  app/src/main/java/com/sw/wordgarden/data/mapper/ServerMapper.kt
  app/src/main/java/com/sw/wordgarden/data/repository/AlarmRepositoryImpl.kt
  app/src/main/java/com/sw/wordgarden/data/repository/DataStoreRepositoryImpl.kt
  app/src/main/java/com/sw/wordgarden/data/repository/QuizRepositoryImpl.kt
  app/src/main/java/com/sw/wordgarden/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/entity/alarm/AlarmEntity.kt
  app/src/main/java/com/sw/wordgarden/domain/entity/user/LoginRequestEntity.kt
  app/src/main/java/com/sw/wordgarden/domain/repository/AlarmRepository.kt
  app/src/main/java/com/sw/wordgarden/domain/repository/DataStoreRepository.kt
  app/src/main/java/com/sw/wordgarden/domain/repository/QuizRepository.kt
  app/src/main/java/com/sw/wordgarden/domain/repository/UserRepository.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/alarm/MakeSharingAlarmUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/alarm/MakeSharingAlarmUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/datastore/GetUidForServiceUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/datastore/GetUidForServiceUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/quiz/common/ShareQuizUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/quiz/common/ShareQuizUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/user/UpdateFcmTokenUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/user/UpdateFcmTokenUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/presentation/event/ErrorMessage.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/alarm/AlarmFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/alarm/AlarmViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/login/LoginFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/login/LoginViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/onboarding/OnBoardingFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/main/fcm/FirebaseMessagingService.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/friends/FriendsFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/quiz/makequiz/MakeQuizFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/quiz/makequiz/MakeQuizViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/quiz/resultquiz/ResultQuizFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/quiz/sharequiz/ShareQuizFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/quiz/sharequiz/ShareQuizViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/quiz/solvequiz/SolveQuizFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/util/Constants.kt
  app/src/main/java/com/sw/wordgarden/presentation/util/KeyboardCleaner.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐞 bug, ✨ feature, 🛠️ refactor

#66 폰트 추가, 적용
  app/src/main/res/font/app_font.xml
  app/src/main/res/font/suite_bold.ttf
  app/src/main/res/font/suite_extra_bold.ttf
  app/src/main/res/font/suite_heavy.ttf
  app/src/main/res/font/suite_light.ttf
  app/src/main/res/font/suite_medium.ttf
  app/src/main/res/font/suite_regular.ttf
  app/src/main/res/font/suite_semi_bold.ttf
  app/src/main/res/values/font_style.xml
  app/src/main/res/values/themes.xml
Labels: 🖌️ design code, 🎨 resource, 📋 style

#65 Feature/word refactor
  app/src/main/java/com/sw/wordgarden/app/di/UseCaseModule.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSource.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSourceImpl.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/retrofit/Service.kt
  app/src/main/java/com/sw/wordgarden/data/dto/WordDto.kt
  app/src/main/java/com/sw/wordgarden/data/repository/WordRepositoryImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/repository/WordRepository.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/DeleteLikedWordUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/DeleteLikedWordUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/GetWeeklyWordListUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/InsertLikedWordUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/InsertLikedWordUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/GetDetailWordUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/GetDetailWordUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/GetWeeklyCategoryWordListUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/GetWeeklyCategoryWordListUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/GetWeeklyWordListUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/GetWeeklyWordListUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/GetWordLikedStatusUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/GetWordLikedStatusUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/InsertLikedWordUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/word/InsertLikedWordUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/DetailWordFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/WordFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/WordViewModel.kt
  app/src/main/res/drawable/ic_full_heart.xml
  app/src/main/res/layout/fragment_detail_word.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#77 garden 리팩토링 마무리
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSourceImpl.kt
  app/src/main/java/com/sw/wordgarden/data/dto/TreeDto.kt
  app/src/main/java/com/sw/wordgarden/data/mapper/ServerMapper.kt
  app/src/main/java/com/sw/wordgarden/domain/entity/TreeEntity.kt
  app/src/main/java/com/sw/wordgarden/presentation/mapper/ModelMapper.kt
  app/src/main/java/com/sw/wordgarden/presentation/model/TreeModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/garden/FlowerBookFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/garden/GardenFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/garden/GardenViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/garden/GetFlowerImg.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/WordFragment.kt
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/drawable/bg_shop_gradient.xml
  app/src/main/res/drawable/ic_cloud1.xml
  app/src/main/res/drawable/ic_cloud2.xml
  app/src/main/res/drawable/ic_cloud3.xml
  app/src/main/res/drawable/ic_growth1.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/ic_star2.xml
  app/src/main/res/drawable/ic_water1.xml
  app/src/main/res/drawable/ic_water2.xml
  app/src/main/res/drawable/ic_water3.xml
  app/src/main/res/layout/fragment_detail_word.xml
  app/src/main/res/layout/fragment_flower_book.xml
  app/src/main/res/layout/fragment_garden.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_shop.xml
  app/src/main/res/layout/fragment_word.xml
  app/src/main/res/layout/item_word.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🛠️ refactor
