Repository SW-WordGarden/Android, pull requests merged in 2024-07, with the labels that each got.

#6 ui package, 디자인 관련 파일 생성
  app/src/main/java/com/sw/wordgarden/presentation/ui/garden/GardenActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/home/HomeActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/LogInActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/MyPageActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/quiz/QuizActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/word/LearningWordActivity.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: 🖌️ design code

#9 마이페이지 뼈대 구현
  app/build.gradle.kts
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/FriendsFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/MyPageActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/QuizzesFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/SettingFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/WeeklyFragment.kt
  app/src/main/res/drawable/answer_rec.xml
  app/src/main/res/drawable/bg_circle_white.xml
  app/src/main/res/drawable/bg_gradient_my.xml
  app/src/main/res/drawable/bg_rectangle_white.xml
  app/src/main/res/drawable/ic_arrow.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_edit.png
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/layout/activity_mypage.xml
  app/src/main/res/layout/activity_quiz.xml
  app/src/main/res/layout/fragment_friends.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_quizzes.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/fragment_weekly.xml
  app/src/main/res/layout/item_my_friends.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🖌️ design code, ✨ feature

#11 회원가입/로그인 기능 구현
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sw/wordgarden/app/AuthCodeHandlerActivity.kt
  app/src/main/java/com/sw/wordgarden/app/WordGardenApplication.kt
  app/src/main/java/com/sw/wordgarden/app/di/NetworkModule.kt
  app/src/main/java/com/sw/wordgarden/app/di/UseCaseModule.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/RetrofitClient.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSource.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSourceImpl.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/Service.kt
  app/src/main/java/com/sw/wordgarden/data/dto/SignUpDto.kt
  app/src/main/java/com/sw/wordgarden/data/mapper/ServerMapper.kt
  app/src/main/java/com/sw/wordgarden/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/entity/QuizEntity.kt
  app/src/main/java/com/sw/wordgarden/domain/entity/QuizListEntity.kt
  app/src/main/java/com/sw/wordgarden/domain/entity/SignUpEntity.kt
  app/src/main/java/com/sw/wordgarden/domain/entity/TreeEntity.kt
  app/src/main/java/com/sw/wordgarden/domain/entity/UserEntity.kt
  app/src/main/java/com/sw/wordgarden/domain/entity/WordEntity.kt
  app/src/main/java/com/sw/wordgarden/domain/repository/UserRepository.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/GetUserInfoUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/GetUserInfoUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/InsertUserUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/InsertUserUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/presentation/model/DefaultEvent.kt
  app/src/main/java/com/sw/wordgarden/presentation/model/UserCheckEvent.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/garden/GardenActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/home/HomeActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/LogInActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/OnBoardingFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/OnBoardingViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/FriendsFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/MyPageActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/MypageFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/QuizzesFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/SettingFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/mypage/WeeklyFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/quiz/QuizActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/util/ToastMaker.kt
  app/src/main/res/drawable/img_google.png
  app/src/main/res/drawable/img_kakao.png
  app/src/main/res/drawable/img_logo.xml
  app/src/main/res/drawable/img_logo_downside.xml
  app/src/main/res/drawable/img_logo_upside.xml
  app/src/main/res/drawable/img_naver.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ⚙️ chore, ✨ feature, 🛠️ refactor

#16 앱 진입 시 스플래시 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/LogInActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/LoginViewModel.kt
  app/src/main/res/drawable/bg_gradient_my.xml
  app/src/main/res/drawable/img_splash.xml
  app/src/main/res/drawable/inset_splash.xml
  app/src/main/res/layout/activity_make_quiz.xml
  app/src/main/res/layout/activity_quiz.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: ⚙️ chore, 🖌️ design code, ✨ feature

#17 기기에 UID 저장 구현
  app/build.gradle.kts
  app/src/main/java/com/sw/wordgarden/app/di/DataSourceModule.kt
  app/src/main/java/com/sw/wordgarden/app/di/DataStoreModule.kt
  app/src/main/java/com/sw/wordgarden/app/di/NetworkModule.kt
  app/src/main/java/com/sw/wordgarden/app/di/RepositoryModule.kt
  app/src/main/java/com/sw/wordgarden/app/di/UseCaseModule.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/local/LocalDataSource.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/local/LocalDataSourceImpl.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/Retrofit/RetrofitClient.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/Retrofit/Service.kt
  app/src/main/java/com/sw/wordgarden/data/datasource/remote/ServerDataSourceImpl.kt
  app/src/main/java/com/sw/wordgarden/data/repository/UidRepositoryImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/repository/UidRepository.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/DeleteUidUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/DeleteUidUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/GetUidUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/GetUidUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/SaveUidUseCase.kt
  app/src/main/java/com/sw/wordgarden/domain/usecase/SaveUidUseCaseImpl.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/LoginFragment.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/sw/wordgarden/presentation/ui/main/MainViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ⚙️ chore, ✨ feature, 🛠️ refactor
